### ISSUE TITLE
No loading of data?

### ISSUE THREAD

**Issue by wsmckenz** [yosiasz/d3-node-express-mongodb#1]
Thanks for the sample. But I dont see where the data is loaded into mongo, as you say in your README. Does this have to be done manually?

**Comment by yosiasz** [comment]
hey I used to have a route that ingested the data, I must have removed it when cleaning things up. apologies. Maybe you could do it manually for now until I sort this out. there is a sample json file in this repo.

**Comment by wsmckenz** [comment]
Ok, np just wanted to make sure I wasn't missing something.
Btw, do I load the data a 1 document with an array data points, or one document for each?

Sent from my Mobile.
wsmckenz@cartewright.com

On Wed, Oct 19, 2016 at 7:57 PM -0500, "Yosi" notifications@github.com wrote:

hey I used to have a route that ingested the data, I must have removed it when cleaning things up. apologies. Maybe you could do it manually for now until I sort this out. there is a sample json file in this repo.

**Comment by yosiasz** [comment]
you can load it as you wish but then you will have to rework your code depending on how you do it

**Comment by yosiasz** [comment]
Ok I see it here in the readme
1. Via web console management ingest the sample data provided to seed 'populations' collection
